mysql:
  service: genCode
  addr: 127.0.0.1:3306
  user: root
  password: 123456
  database: activiti
  charset: utf8mb4
  timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

log:
  service: genCode
  level: info
  stdout: true
  dir: log
  extra_keys:
    - requestId

code_gen:
  mode: api
  service_name: workflow
  module:
    tpl_dir: internal/resource/codeTpl/module
    internal_app_root_dir: internal/app
    project_root_dir: go-gin-workflow
    description: 审批流程实例
    api_doc_tag: 审批流程实例
    api_group: process
    api_prefix: /workflow/process/
    package_name: process
    table_name: proc_inst
  model:
    tpl_dir: internal/resource/codeTpl/model
    internal_app_root_dir: internal/app
    project_root_dir: go-gin-workflow
    description: 身份链接历史记录表
    package_name: process
    table_name: identitylink_history
  api:
    tpl_dir: internal/resource/codeTpl/api
    internal_app_root_dir: internal/app
    project_root_dir: go-gin-workflow
    description: 抄送我的的流程实例分页列表
    package_name: process
    target_filename: proc_inst.go
    http_method: GET
    function_name: TodoPageList
    api_doc_tag: 审批流程实例
    api_group: process
    api_prefix: /workflow/process/
    api_suffix: ccPageList
    routerGroup: processGroup
