mysql:
  service: genCode
  addr: 127.0.0.1:3306
  user: root
  password: 123456
  database: activiti
  charset: utf8mb4
  timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

log:
  service: genCode
  level: info
  stdout: true
  dir: log
  extra_keys:
    - requestId

code_gen:
  mode: api
  module:
    tpl_dir: internal/resource/codeTpl/module
    internal_app_root_dir: internal/workflow
    project_root_dir: go-workflow-engine
    description: 审批流程
    api_doc_tag: 审批流程
    api_group: procdef
    api_prefix: /workflow/procdef/
    package_name: procdef
    table_name: procdef
  model:
    tpl_dir: internal/resource/codeTpl/model
    internal_app_root_dir: internal/workflow
    project_root_dir: go-workflow-engine
    description: 审批流程定义历史记录
    package_name: procdef
    table_name: procdef_history
  api:
    tpl_dir: internal/resource/codeTpl/api
    internal_app_root_dir: internal/workflow
    project_root_dir: go-workflow-engine
    description: 审批流程保存（token）
    package_name: procdef
    target_filename: procdef.go
    http_method: POST
    function_name: SaveByToken
    api_doc_tag: 用户管理
    api_group: user
    api_prefix: /workflow/user/
    api_suffix: disable
    routerGroup: userGroup
